<script lang="ts">
  import { onMount } from 'svelte'; import Check from 'lucide-svelte/icons/check'; import Copy from 'lucide-svelte/icons/copy'; import KeyRound from 'lucide-svelte/icons/key-round';
  import PageHeader from '$lib/components/PageHeader.svelte'; import AsyncState from '$lib/components/AsyncState.svelte'; import { api, shortDate } from '$lib/api/client';
  let apps=$state<any[]>([]); let loading=$state(true); let error=$state(''); let name=$state('Noura buyer agent'); let secret=$state(''); let copied=$state(false);
  onMount(load); async function load(){try{apps=(await api<{items:any[]}>('/api/v1/developer-applications')).items;}catch(cause){error=cause instanceof Error?cause.message:String(cause);}finally{loading=false;}}
  async function createApp(){error='';try{await api('/api/v1/developer-applications',{method:'POST',body:JSON.stringify({name,owner:{type:'HUMAN',display_name:'Demo buyer principal',email:'buyer.agent@thikra.demo'},redirect_uris:['http://localhost:43191'],webhook_allowlist:[]})});await load();}catch(cause){error=cause instanceof Error?cause.message:String(cause);}}
  async function issueKey(applicationId:string){error='';try{const result:any=await api(`/api/v1/developer-applications/${applicationId}/api-keys`,{method:'POST',body:JSON.stringify({name:'Agent Gateway key',scopes:['services:read','quotes:create','orders:create','orders:read','payments:create','deliverables:read','disputes:create','webhooks:manage']})});secret=result.secret;await load();}catch(cause){error=cause instanceof Error?cause.message:String(cause);}}
  async function copy(){await navigator.clipboard.writeText(secret);copied=true;}
</script>
<PageHeader eyebrow="Developer identity" title="Applications and scoped API keys." description="Full secrets appear once. Persistence contains only an HMAC-peppered hash, prefix, scope set, and lifecycle timestamps.">
  {#snippet actions()}<a class="btn btn-secondary" href="/developers">Authentication guide</a>{/snippet}
</PageHeader>
{#if secret}<section class="notice-secret"><KeyRound size={22}/><div><strong>Copy this API key now</strong><p class="mono">{secret}</p><span>It cannot be displayed again.</span></div><button class="btn btn-secondary" onclick={copy}>{#if copied}<Check size={14}/> Copied{:else}<Copy size={14}/> Copy{/if}</button></section>{/if}
<section class="card card-pad" style="margin-bottom:20px"><h2>Create developer application</h2><div class="form-grid"><div class="field"><label for="app-name">Application name</label><input id="app-name" bind:value={name}/></div><div class="field" style="align-self:end"><button class="btn btn-primary" onclick={createApp}>Create application</button></div></div></section>
<AsyncState {loading} {error}><section class="grid grid-2">{#each apps as app (app.id)}<article class="card card-pad"><div class="card-head-inline"><div><span class="badge" data-tone="success">{app.status}</span><h2>{app.name}</h2></div><button class="btn btn-primary" onclick={()=>issueKey(app.id)}><KeyRound size={15}/> Issue key</button></div><p class="small muted">Owner principal {app.owner_principal_id} · created {shortDate(app.created_at)}</p><h3>Keys</h3>{#if app.api_keys.length}{#each app.api_keys as key}<div class="key-row"><div><strong>{key.name}</strong><span class="mono">{key.prefix}…</span></div><span class="small muted">last used {shortDate(key.last_used_at)}</span></div>{/each}{:else}<p class="muted">No keys issued.</p>{/if}</article>{/each}</section></AsyncState>
